name: idkollen_client
description: Dart client for the IDkollen REST API.
version: 0.1.0
repository: https://github.com/idkollen/idk-clients

environment:
  sdk: ^3.0.0

dependencies:
  http: ^1.2.0
  http_parser: ^4.0.0

dev_dependencies:
  test: ^1.25.0
  lints: ^4.0.0
